### ISSUE TITLE
Review introduction of Formik

### ISSUE THREAD

**Issue by tatsushitoji** [nkgrnkgr/put-your-hands-up#2]
I suggest that we use [Formik](https://github.com/jaredpalmer/formik).
I think this component lead us more better programming around form 🤔

**Comment by nkgrnkgr** [comment]
Thank you for introducing Formik. I will use this!

**Comment by tatsushitoji** [comment]
Shall I close this issue ?

**Comment by nkgrnkgr** [comment]
OK！
I close this issue.

Thank you for your issue🙏🏻
